- name: Singapore Government Tech Stack
  description: A common platform that streamlines and simplifies the development process
  items:
    - Overview
    - APEX
    - Cloud File Transfer

- name: Tech for Public Good
  description: Technologies developed to the needs of citizens and businesses and empower them to achieve a greater quality of life
  items:
    - Overview
    - eCanvas
    - ePad
    - GatherSG
    - LiveSG
    - Personal Alert Button