- name: Overview
  description: Overview of products prototype
  is_icon: false

- name: All Products
  description: Government-built open-source technologies and tools
  is_icon: true
  icon_class: sgds-icon-grid

- name: Collections
  path: /products/overview/#collections
  description: Digital Solutions for a 21st Century Pandemic
  items:
    - Open-source
    - Singapore Government Tech Stack

- name: Categories
  path: /products/overview/#categories
  description: Government-built open-source technologies and tools
  items:
    - Digital Solutions to Address COVID-19
    - Open-source
    - Analytics
    - Blockchain
    - Content Management
    - Data and APIs
    - Design
    - DevOps
    - Digital Identity
    - Infrastructure and Hosting
    - Sensor Platforms and Internet of Things
    - Platform
    - Productivity Tools
