- name: Overview
  description: Overview of products prototype

- name: All Products
  description: Government-built open-source technologies and tools

- name: Collections
  path: /products/overview/#collections
  description: Digital Solutions for a 21st Century Pandemic
  items:
    - Popular
    - What's New
    - Covid-19

- name: Categories
  path: /products/overview/#categories
  description: Government-built open-source technologies and tools
  items:
    - Digital Solutions to Address COVID-19
    - Open-source
    - Analytics
    - Blockchain
    - Content Management
    - Data and APIs
    - Design
    - DevOps
    - Digital Identity
    - Infrastructure and Hosting
    - Sensor Platforms and Internet of Things
    - Platform
    - Productivity Tools
