- name: Open-source
  description: A wide range of open-source technologies by Government agencies
  items:
    - Overview
    - API Exchange (APEX)
    - FormSG
    - Go.gov.sg
    - TraceTogether
    - VigilantGantry
    
- name: Singapore Government Tech Stack
  description: A common platform that streamlines and simplifies the development process
  items:
    - Overview
    - API Exchange (APEX)
    - Cloud File Transfer
