- name: Overview
  description: Overview of products prototype

- name: All Products
  description: Government-built open-source technologies and tools

- name: Collections
  path: /products-proto/overview/#collections
  description: Digital Solutions for a 21st Century Pandemic
  items:
    - Popular
    - What's New
    - Covid-19

- name: Categories
  path: /products-proto/overview/#categories
  description: Government-built open-source technologies and tools
  items:
    - Analytics
