- name: Open-source
  description: A wide range of open-source technologies by government agencies
  items:
    - Overview
    - API Exchange (APEX)
    - FormSG
    - Go.gov.sg
    - Singapore Government Design System
    - TraceTogether
    - VigilantGantry
    
- name: Singapore Government Tech Stack
  description: A common government platform that streamlines and simplifies the development process
  items:
    - Overview
    - Asynchronous Data Exchange
    - APEX
    - Cloud File Transfer
    - Container Stack
    - Government on Commercial Cloud
    - SHIP-HATS
    - StackOps
