- name: Open-source
  description: A wide range of open-source technologies by Government agencies
  items:
    - Overview
    
- name: Singapore Government Tech Stack
  description: A common platform that streamlines and simplifies the development process
  items:
    - Overview
    - APEX
    - Cloud File Transfer
